---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: update facts
      setup:
      vars:
        ansible_python_interpreter: /usr/bin/python3

    - name: check dictribution
      ansible.builtin.debug:
        msg: "ansible_distribution: {{ ansible_distribution }}"

    - name: test ubuntu
      ansible.builtin.debug:
        msg: "This is the effective test ubuntu"
      when: ansible_distribution == 'Ubuntu'

    - name: test centos
      ansible.builtin.debug:
        msg: "This is the effective test centos"
      when: ansible_distribution == 'CentOS'

    - name: Include role
      include_role:
        name: "vector-role"